window.HABLA_DATA = {
  gloss: {
    a:"un / una", about:"sobre", after:"después", again:"otra vez",
    all:"todo", also:"también", always:"siempre", am:"soy / estoy",
    and:"y", another:"otro", any:"cualquier", anything:"cualquier cosa",
    are:"eres / están", around:"alrededor", as:"como", ask:"preguntar",
    at:"en / a",
    be:"ser / estar", because:"porque", been:"sido / estado",
    before:"antes", better:"mejor", big:"grande",
    breakfast:"desayuno", but:"pero", by:"por",
    can:"puedo / puedes", come:"venir", could:"podría",
    day:"día", dinner:"cena", do:"hacer", does:"hace",
    don't:"no", down:"abajo",
    eat:"comer", even:"incluso", ever:"alguna vez", every:"cada",
    feel:"sentir", few:"unos pocos", first:"primero",
    for:"para / por", from:"de",
    get:"conseguir / llegar", go:"ir", going:"yendo / voy a",
    good:"bueno", got:"tengo / conseguí",
    had:"tuve", happy:"feliz", has:"tiene", have:"tener",
    help:"ayuda", her:"su / ella", here:"aquí", him:"él",
    home:"casa", how:"cómo",
    i:"yo", if:"si", in:"en", into:"en / hacia", is:"es / está",
    it:"eso", just:"solo / recién",
    know:"saber",
    later:"más tarde", let:"dejar", like:"gustar / como",
    little:"un poco / pequeño", look:"mirar", love:"amor / querer",
    make:"hacer", me:"me / mí", mean:"significar / querer decir",
    more:"más", much:"mucho", my:"mi",
    need:"necesitar", never:"nunca", next:"siguiente",
    nice:"agradable", night:"noche", no:"no", not:"no",
    now:"ahora",
    of:"de", ok:"está bien", okay:"está bien", on:"en",
    one:"uno", or:"o", other:"otro", our:"nuestro", out:"fuera",
    please:"por favor",
    really:"de verdad", right:"bien / derecha",
    said:"dijo", same:"igual", say:"decir", see:"ver",
    she:"ella", should:"debería", so:"entonces / tan",
    some:"algo / algunos", something:"algo", sorry:"lo siento",
    still:"todavía", sure:"claro",
    take:"tomar", tell:"decir", than:"que", that:"eso / que",
    the:"el / la", then:"entonces", there:"allí", they:"ellos",
    think:"pensar", this:"esto", time:"tiempo / vez",
    to:"a / para", today:"hoy", tomorrow:"mañana",
    too:"también / demasiado", try:"intentar",
    understand:"entender", up:"arriba", us:"nosotros",
    very:"muy",
    want:"querer", was:"era / estaba", we:"nosotros",
    well:"bien", what:"qué", when:"cuándo", where:"dónde",
    which:"cuál", who:"quién", why:"por qué", will:"voy a",
    with:"con", work:"trabajo", would:"haría",
    yes:"sí", you:"tú / usted", your:"tu"
  },

  unigrams: {
    i:[["am",9],["want",8],["don't",8],["think",7],["need",6],["love",6],["have",6],["can",5],["feel",5],["know",4]],
    i'm:[["sorry",8],["trying",6],["happy",5],["going",5],["not",4],["a",3]],
    i'd:[["like",10],["love",4]],
    you:[["are",6],["can",6],["want",5],["look",4],["mean",4],["know",3]],
    we:[["can",6],["should",5],["are",4],["need",4],["could",3]],
    they:[["are",5],["don't",3],["said",3]],
    it:[["is",7],["was",4],["means",4],["looks",3]],
    this:[["is",8],["means",4],["looks",3]],
    that:[["is",6],["was",4],["sounds",3]],
    my:[["name",6],["love",4],["family",4],["work",3]],
    your:[["name",5],["family",3],["day",3]],
    the:[["same",4],["best",3],["other",3]],
    a:[["little",7],["lot",5],["good",4],["bit",4]],
    to:[["be",6],["go",5],["see",4],["say",4],["do",3]],
    for:[["you",6],["me",5],["a",4],["dinner",3]],
    of:[["course",6],["the",4],["my",3]],
    in:[["the",6],["a",4],["love",3]],
    on:[["the",5],["my",4],["time",3]],
    at:[["home",5],["work",4],["the",3]],
    with:[["you",8],["me",4],["my",3]],
    and:[["i",6],["then",4],["you",3]],
    but:[["i",7],["it",4],["we",3]],
    because:[["i",6],["you",4],["it",3]],
    if:[["you",7],["i",5],["we",3]],
    when:[["you",5],["i",4],["we",3]],
    what:[["do",7],["does",5],["is",5],["are",4]],
    how:[["are",8],["do",6],["can",5],["was",3]],
    where:[["is",7],["are",5],["do",3]],
    why:[["did",5],["do",5],["is",3]],
    can:[["you",8],["i",6],["we",4]],
    could:[["you",8],["i",4],["we",3]],
    would:[["you",6],["like",5],["love",3]],
    do:[["you",10],["not",4],["we",3]],
    don't:[["know",7],["understand",6],["want",5],["worry",4]],
    want:[["to",10],["you",3]],
    need:[["to",8],["help",4],["you",3]],
    like:[["to",6],["you",5],["this",3]],
    love:[["you",10],["this",3]],
    going:[["to",12]],
    have:[["to",6],["a",5],["been",3]],
    feel:[["like",5],["happy",4],["better",3]],
    think:[["that",6],["so",5],["you",3]],
    know:[["that",5],["how",4],["what",3]],
    please:[["repeat",6],["speak",5],["help",4],["slow",4]],
    sorry:[["i",6],["about",4]],
    thank:[["you",12]],
    thanks:[["for",6],["so",3]],
    hello:[["how",6],["i",3]],
    hi:[["how",6],["i",3]],
    good:[["morning",7],["night",6],["afternoon",5],["to",3]],
    see:[["you",8],["if",3]],
    let:[["me",6],["us",3]],
    let's:[["go",6],["try",4],["eat",3]],
    speak:[["slowly",8],["english",5]],
    repeat:[["that",8],["please",6]],
    help:[["me",8],["you",3]]
  },

  bigrams: {
    "i am":[["sorry",6],["trying",5],["happy",5],["learning",5],["so",3]],
    "i want":[["to",12]],
    "i don't":[["know",7],["understand",7],["want",4]],
    "i think":[["that",6],["so",5],["you",3]],
    "i need":[["to",7],["help",4],["you",3]],
    "i love":[["you",12],["this",3]],
    "i can":[["try",4],["see",3],["help",3]],
    "i feel":[["happy",5],["better",4],["like",3]],
    "i'd like":[["to",8],["a",4]],
    "i'm sorry":[["i",6],["for",4]],
    "i'm trying":[["to",8]],
    "you are":[["so",5],["beautiful",4],["kind",4]],
    "you can":[["help",4],["say",3],["repeat",3]],
    "how are":[["you",12]],
    "how do":[["you",8],["i",4]],
    "what do":[["you",8]],
    "what does":[["that",7],["this",5]],
    "where is":[["the",6],["it",3]],
    "can you":[["repeat",8],["help",7],["speak",6],["say",4]],
    "could you":[["repeat",7],["help",6],["speak",5]],
    "do you":[["want",6],["understand",5],["like",4],["have",3]],
    "don't know":[["how",5],["what",4],["if",3]],
    "don't understand":[["that",5],["yet",4]],
    "want to":[["say",6],["go",5],["tell",4],["eat",3],["learn",3]],
    "need to":[["say",4],["go",4],["practice",3]],
    "going to":[["try",5],["say",4],["go",3]],
    "have to":[["go",5],["say",3]],
    "thank you":[["so",6],["for",5]],
    "so much":[["for",4]],
    "please repeat":[["that",8]],
    "please speak":[["slowly",8],["slower",6]],
    "speak slowly":[["please",8]],
    "let me":[["try",6],["see",4],["say",3]],
    "see you":[["later",6],["tomorrow",5],["soon",4]],
    "good morning":[["how",5],["my",3]],
    "good night":[["i",5],["sleep",3]],
    "i love you":[["so",6],["too",4]],
    "how are you":[["today",6],["feeling",3]]
  },

  sentences: {
    "i": [
      ["I am learning English for you.", "Estoy aprendiendo inglés por ti."],
      ["I don't understand. Can you repeat that?", "No entiendo. ¿Puedes repetir eso?"],
      ["I want to say this correctly.", "Quiero decir esto correctamente."]
    ],
    "i want": [
      ["I want to tell you something.", "Quiero decirte algo."],
      ["I want to go with you.", "Quiero ir contigo."]
    ],
    "i love": [
      ["I love you.", "Te quiero."],
      ["I love you so much.", "Te quiero mucho."]
    ],
    "i don't": [
      ["I don't understand yet.", "Todavía no entiendo."],
      ["I don't know how to say it.", "No sé cómo decirlo."]
    ],
    "i'm sorry": [
      ["I'm sorry. I didn't mean that.", "Lo siento. No quise decir eso."],
      ["I'm sorry I was late.", "Siento haber llegado tarde."]
    ],
    "can you": [
      ["Can you repeat that, please?", "¿Puedes repetir eso, por favor?"],
      ["Can you speak more slowly?", "¿Puedes hablar más despacio?"]
    ],
    "how are": [
      ["How are you today?", "¿Cómo estás hoy?"],
      ["How are you feeling?", "¿Cómo te sientes?"]
    ],
    "what does": [
      ["What does that mean?", "¿Qué significa eso?"],
      ["What does this word mean?", "¿Qué significa esta palabra?"]
    ],
    "please": [
      ["Please speak slowly.", "Por favor habla despacio."],
      ["Please help me say this.", "Por favor ayúdame a decir esto."]
    ],
    "thank you": [
      ["Thank you so much.", "Muchas gracias."],
      ["Thank you for being patient.", "Gracias por tu paciencia."]
    ],
    "hello": [
      ["Hello, how are you?", "Hola, ¿cómo estás?"],
      ["Hi, I missed you.", "Hola, te extrañé."]
    ]
  }
};
