/* Conversational Spanish next-word model + compact glosses.
   Designed for spoken everyday Spanish, not literary text. */
window.HABLA_DATA = {
  gloss: {
    a:"to / at", ahora:"now", al:"to the", algo:"something", alguien:"someone",
    alguna:"some", algún:"some", allí:"there", antes:"before", aquí:"here",
    así:"like that", aunque:"although", ayer:"yesterday",
    bien:"well / fine", bueno:"well / good",
    casa:"house / home", casi:"almost", cena:"dinner", cierto:"true / certain",
    claro:"of course / clear", cómo:"how", comida:"food / meal",
    con:"with", conseguir:"to get / manage", cuenta:"bill / account",
    cuando:"when", cuanto:"how much",
    de:"of / from", decir:"to say", dejar:"to leave / let",
    del:"of the", después:"after", día:"day", dice:"says",
    digo:"I say", disculpa:"sorry / excuse me",
    dónde:"where", dos:"two", durante:"during",
    el:"the", ella:"she", ellos:"they", en:"in / on",
    entonces:"then / so", entre:"between", esa:"that", ese:"that",
    eso:"that", esta:"this", está:"is / stays", estaban:"they were",
    estábamos:"we were", estado:"been / state", estáis:"you all are",
    estamos:"we are", están:"they are", estar:"to be", este:"this",
    esto:"this", estoy:"I am",
    favor:"favor", fin:"end", fue:"was",
    gente:"people", gracias:"thank you", grande:"big",
    hablar:"to speak", hace:"ago / it does", hacer:"to do / make",
    hacia:"toward", hay:"there is", he:"I have",
    hola:"hello", hora:"hour / time", hoy:"today",
    ir:"to go", iba:"I/he was going",
    la:"the / it", las:"the", le:"him/her", les:"them",
    lo:"it / the", los:"the", luego:"later / then",
    más:"more", me:"me", mejor:"better", menos:"less",
    mi:"my", mí:"me", mientras:"while",
    mira:"look", mismo:"same", momento:"moment",
    mucho:"a lot", muchos:"many", muy:"very",
    nada:"nothing", nadie:"nobody", necesito:"I need",
    no:"no / not", nos:"us", nosotros:"we",
    nunca:"never",
    o:"or", otra:"other", otro:"other",
    para:"for / in order to", parece:"it seems",
    pero:"but", poco:"a little", por:"for / by",
    porque:"because", puedo:"I can", puedes:"you can",
    pues:"well / so",
    que:"that / which / what", qué:"what", querer:"to want",
    quería:"I wanted", quiere:"wants", quieren:"they want",
    quiero:"I want", quisiera:"I would like",
    se:"oneself", sí:"yes", si:"if", siempre:"always",
    siento:"I feel / I'm sorry", sin:"without",
    sobre:"about / on", solo:"only / alone",
    son:"they are", soy:"I am", su:"his / her / their",
    también:"also", tampoco:"neither", tan:"so",
    tanto:"so much", te:"you", tener:"to have",
    tengo:"I have", tienes:"you have",
    tiempo:"time / weather", tiene:"has",
    todavía:"still", todo:"everything / all",
    trabajo:"work", tres:"three", tu:"your", tú:"you",
    un:"a", una:"a", unos:"some",
    usted:"you (formal)",
    vamos:"let's go / we go", veo:"I see",
    ver:"to see", vez:"time (occasion)",
    voy:"I go",
    ya:"already / now", yo:"I"
  },

  /* last-token -> weighted next words */
  unigrams: {
    yo:[["estoy",9],["quiero",9],["voy",8],["creo",7],["tengo",7],["no",6],["necesito",6],["puedo",5],["también",4],["soy",4]],
    me:[["gusta",10],["parece",6],["puedes",6],["llamo",5],["siento",5],["gustaría",5],["encanta",4],["puedo",4],["voy",3]],
    te:[["gusta",6],["puedo",6],["voy",5],["parece",4],["quiero",4],["importo",3]],
    mi:[["nombre",6],["casa",5],["amigo",4],["trabajo",4],["familia",4],["pregunta",3]],
    tu:[["nombre",5],["casa",4],["opinión",3]],
    el:[["problema",6],["otro",4],["baño",4],["trabajo",4],["día",3],["menú",3],["precio",3]],
    la:[["verdad",6],["casa",5],["cuenta",5],["gente",4],["comida",4],["hora",3],["calle",3]],
    un:[["poco",7],["momento",6],["café",5],["favor",4],["rato",4],["taxi",3],["problema",3]],
    una:[["pregunta",7],["mesa",5],["cerveza",4],["cosa",4],["hora",3],["idea",3]],
    de:[["la",7],["el",6],["nada",4],["acuerdo",4],["verdad",3],["comer",3]],
    a:[["la",8],["el",6],["ver",5],["casa",4],["comer",4],["dónde",3],["mí",3]],
    al:[["baño",6],["trabajo",5],["centro",4],["médico",3],["final",3]],
    en:[["la",7],["el",6],["casa",5],["realidad",4],["serio",3],["español",3]],
    por:[["favor",12],["eso",6],["qué",6],["aquí",3],["allí",3]],
    para:[["mí",6],["que",5],["ir",4],["comer",3],["hoy",3],["llevar",3]],
    que:[["no",6],["sí",5],["está",4],["quiero",4],["puedo",4],["vamos",3],["tal",3]],
    no:[["sé",10],["puedo",7],["quiero",6],["entiendo",6],["me",5],["hay",4],["pasa",4],["te",3]],
    sí:[["claro",6],["pues",5],["quiero",4],["por",3],["eso",3]],
    qué:[["tal",8],["pasa",6],["hora",5],["quieres",5],["significa",4],["hay",4],["más",3]],
    cómo:[["estás",9],["te",6],["se",5],["puedo",4],["está",4],["vas",3]],
    dónde:[["está",8],["queda",5],["puedo",4],["estáis",3],["vives",3]],
    cuándo:[["es",5],["vamos",4],["puedes",3],["llegas",3]],
    porqué:[["no",4],["es",3]],
    porque:[["no",5],["quiero",4],["es",4],["tengo",3]],
    pero:[["no",6],["creo",4],["es",4],["bueno",3],["también",3]],
    y:[["luego",5],["también",5],["no",4],["después",4],["tú",3]],
    o:[["no",5],["algo",4],["mejor",3],["qué",3]],
    pues:[["sí",6],["no",5],["entonces",4],["bueno",3],["nada",3]],
    entonces:[["qué",6],["vamos",5],["no",4],["sí",3]],
    bueno:[["pues",6],["entonces",4],["voy",3],["está",3]],
    ahora:[["mismo",6],["no",4],["voy",4],["sí",3]],
    ya:[["sé",5],["voy",5],["está",4],["casi",3],["no",3]],
    también:[["quiero",5],["me",4],["puedo",3],["está",3]],
    muy:[["bien",8],["bueno",5],["interesante",4],["cansado",3],["importante",3]],
    más:[["tarde",6],["o",4],["despacio",4],["tiempo",3],["agua",3]],
    hay:[["un",6],["una",5],["que",4],["algo",4],["gente",3]],
    es:[["que",8],["un",5],["una",4],["muy",4],["mejor",3],["verdad",3]],
    está:[["bien",7],["aquí",5],["lejos",4],["cerca",4],["bueno",3],["cerrado",3]],
    estoy:[["bien",6],["aquí",5],["aprendiendo",5],["buscando",4],["cansado",4],["listo",3],["tratando",3]],
    somos:[["de",4],["un",3]],
    son:[["de",4],["muy",3],["las",3]],
    voy:[["a",12],["al",6],["para",3]],
    vamos:[["a",10],["al",5],["para",3]],
    quiero:[["ir",7],["un",5],["una",5],["decir",4],["saber",4],["pedir",4],["comer",4],["hablar",3]],
    quieres:[["ir",5],["algo",4],["comer",4],["decir",3]],
    quisiera:[["un",6],["una",6],["ir",4],["pedir",4],["saber",3]],
    puedo:[["ir",5],["tener",4],["ayudarte",4],["pedir",3],["hablar",3]],
    puedes:[["ayudarme",6],["repetir",6],["hablar",4],["decirme",4],["venir",3]],
    tengo:[["que",8],["un",5],["una",4],["hambre",4],["frío",3],["tiempo",3]],
    tienes:[["que",5],["tiempo",4],["un",3]],
    necesito:[["ayuda",6],["un",5],["una",4],["ir",3],["practicar",3]],
    creo:[["que",12]],
    pienso:[["que",10]],
    parece:[["que",7],["bien",4],["interesante",3]],
    gusta:[["mucho",6],["el",4],["la",4],["más",3]],
    gustaría:[["ir",5],["un",4],["saber",3],["probar",3]],
    siento:[["mucho",6],["que",4]],
    gracias:[["por",7],["mil",3]],
    favor:[["me",5],["puedes",5],["una",3]],
    hola:[["qué",6],["buenos",5],["cómo",4]],
    buenos:[["días",8]],
    buenas:[["tardes",7],["noches",6]],
    hasta:[["luego",7],["mañana",6],["pronto",4]],
    lo:[["siento",8],["que",5],["sé",4],["mismo",3]],
    se:[["puede",5],["llama",4],["me",3],["te",3]],
    con:[["mucho",4],["el",4],["la",4],["gusto",4],["permiso",3]],
    sin:[["problema",6],["falta",3]],
    sobre:[["la",4],["el",4],["eso",3]],
    entre:[["semana",3],["nosotros",3]],
    después:[["de",6],["vamos",3]],
    antes:[["de",7]],
    durante:[["el",4],["la",3]],
    desde:[["hace",4],["aquí",3]],
    hacia:[["allá",3],["el",3]],
    ir:[["a",10],["al",6],["con",3]],
    comer:[["algo",5],["aquí",3],["juntos",3]],
    hablar:[["más",5],["despacio",5],["español",5],["con",3]],
    pedir:[["la",6],["un",5],["una",4]],
    ver:[["si",5],["el",4],["la",3]],
    saber:[["si",5],["dónde",4],["qué",4]],
    decir:[["que",5],["algo",3]],
    hacer:[["el",4],["una",4],["falta",3]],
    casa:[["por",3],["ahora",3]],
    trabajo:[["mañana",3],["hoy",3]],
    español:[["un",4],["más",4],["por",3]],
    despacio:[["por",6]],
    repetir:[["por",6],["eso",3]],
    cuenta:[["por",5],["cuando",3]],
    baño:[["por",4]],
    agua:[["por",4],["con",3]],
    café:[["con",4],["por",3]],
    mesa:[["para",6],["cerca",3]]
  },

  /* last two tokens "w1 w2" -> next */
  bigrams: {
    "yo estoy":[["aprendiendo",6],["bien",5],["buscando",4],["tratando",4],["aquí",3]],
    "yo quiero":[["ir",7],["decir",5],["pedir",5],["saber",4],["practicar",4],["comer",4]],
    "yo voy":[["a",12]],
    "yo creo":[["que",12]],
    "yo tengo":[["que",7],["un",4],["una",3],["hambre",3]],
    "yo no":[["sé",7],["puedo",5],["quiero",5],["entiendo",4]],
    "yo puedo":[["ir",4],["ayudar",3],["hablar",3]],
    "me gusta":[["mucho",7],["el",5],["la",5],["cuando",3]],
    "me puedes":[["ayudar",6],["repetir",5],["decir",4],["traer",3]],
    "me parece":[["bien",6],["que",5],["interesante",3]],
    "me gustaría":[["ir",5],["un",4],["pedir",4],["probar",3]],
    "por favor":[["me",6],["puedes",6],["una",4],["el",3]],
    "qué tal":[["estás",6],["te",4],["va",4]],
    "qué pasa":[["si",4],["aquí",3],["contigo",3]],
    "qué hora":[["es",10]],
    "cómo estás":[["hoy",4],["tú",3]],
    "cómo se":[["dice",8],["llama",6]],
    "dónde está":[["el",7],["la",7],["el baño",4]],
    "voy a":[["ir",6],["pedir",5],["comer",4],["practicar",4],["la",3],["ver",3]],
    "vamos a":[["ir",6],["comer",5],["ver",4],["pedir",3]],
    "quiero ir":[["a",8],["al",6]],
    "quiero un":[["café",5],["poco",4],["agua",3],["taxi",3]],
    "quiero una":[["mesa",5],["cerveza",4],["pregunta",3]],
    "quiero pedir":[["la",6],["un",4],["una",3]],
    "quiero saber":[["si",6],["dónde",4],["cómo",3]],
    "quisiera un":[["café",5],["agua",4],["momento",3]],
    "quisiera una":[["mesa",6],["cerveza",4],["pregunta",3]],
    "tengo que":[["ir",7],["pedir",4],["practicar",4],["trabajar",3]],
    "hay un":[["problema",5],["restaurante",3],["baño",3]],
    "hay una":[["mesa",5],["pregunta",3]],
    "es que":[["no",6],["estoy",4],["quiero",3],["no entiendo",3]],
    "no sé":[["si",7],["qué",5],["cómo",4],["dónde",3]],
    "no puedo":[["ir",4],["hablar",3],["venir",3]],
    "no quiero":[["ir",4],["eso",3]],
    "no entiendo":[["bien",5],["qué",4],["el",3]],
    "lo siento":[["mucho",6],["pero",4]],
    "está bien":[["así",4],["para",3],["gracias",3]],
    "muy bien":[["gracias",5],["entonces",3]],
    "más despacio":[["por",8]],
    "hablar despacio":[["por",6]],
    "ir a":[["la",7],["casa",5],["comer",4],["ver",3]],
    "ir al":[["baño",7],["trabajo",4],["centro",3]],
    "pedir la":[["cuenta",10]],
    "en la":[["casa",5],["mañana",3],["calle",3],["mesa",3]],
    "en el":[["trabajo",4],["centro",3],["baño",3]],
    "a la":[["casa",5],["derecha",4],["izquierda",3],["mesa",3]],
    "a ver":[["si",6],["qué",3]],
    "creo que":[["sí",6],["no",5],["está",4],["voy",3]],
    "pienso que":[["es",5],["sí",4],["no",3]],
    "gracias por":[["tu",5],["la",4],["ayudarme",4]],
    "buenos días":[["cómo",4],["qué",3]],
    "hasta luego":[["gracias",3]],
    "sí claro":[["cómo",3],["puedes",3]],
    "una mesa":[["para",8]],
    "mesa para":[["dos",8],["tres",5],["cuatro",4]],
    "un café":[["por",5],["con",4]],
    "con leche":[["por",5]],
    "el baño":[["por",5]],
    "la cuenta":[["por",8]],
    "por eso":[["no",4],["quiero",3],["estoy",3]],
    "antes de":[["ir",5],["comer",3]],
    "después de":[["comer",4],["esto",3]],
    "tratar de":[["decir",4],["hablar",4],["pedir",3]],
    "aprendiendo español":[["y",3],["pero",3]],
    "puedes repetir":[["por",8]],
    "puedes ayudar":[["me",4],["con",4]],
    "me ayudas":[["con",5],["por",3]]
  },

  sentences: {
    "yo": [
      ["Yo estoy aprendiendo español.", "I am learning Spanish."],
      ["Yo quiero practicar un poco más.", "I want to practice a little more."],
      ["Yo no entiendo esa palabra.", "I don't understand that word."]
    ],
    "yo quiero": [
      ["Yo quiero ir al baño.", "I want to go to the bathroom."],
      ["Yo quiero pedir la cuenta.", "I want to ask for the check."],
      ["Yo quiero hablar más despacio.", "I want to speak more slowly."]
    ],
    "yo voy": [
      ["Yo voy a pedir un café.", "I'm going to order a coffee."],
      ["Yo voy a intentarlo otra vez.", "I'm going to try it again."]
    ],
    "me": [
      ["Me puedes repetir eso, por favor.", "Can you repeat that, please."],
      ["Me gusta mucho este lugar.", "I like this place a lot."]
    ],
    "me puedes": [
      ["Me puedes ayudar con esto, por favor.", "Can you help me with this, please."],
      ["Me puedes hablar más despacio.", "Can you speak more slowly."]
    ],
    "por favor": [
      ["Por favor, una mesa para dos.", "Please, a table for two."],
      ["Por favor, la cuenta.", "The check, please."]
    ],
    "dónde está": [
      ["¿Dónde está el baño?", "Where is the bathroom?"],
      ["¿Dónde está la estación?", "Where is the station?"]
    ],
    "qué": [
      ["¿Qué hora es?", "What time is it?"],
      ["¿Qué significa esa palabra?", "What does that word mean?"]
    ],
    "cómo": [
      ["¿Cómo se dice esto en español?", "How do you say this in Spanish?"],
      ["¿Cómo estás hoy?", "How are you today?"]
    ],
    "no": [
      ["No entiendo bien.", "I don't understand well."],
      ["No sé cómo decirlo.", "I don't know how to say it."]
    ],
    "no sé": [
      ["No sé si eso está bien.", "I don't know if that's okay."],
      ["No sé cómo pronunciarlo.", "I don't know how to pronounce it."]
    ],
    "tengo": [
      ["Tengo que irme.", "I have to leave."],
      ["Tengo una pregunta.", "I have a question."]
    ],
    "quisiera": [
      ["Quisiera una mesa para dos.", "I would like a table for two."],
      ["Quisiera pedir la cuenta.", "I would like to ask for the check."]
    ],
    "vamos": [
      ["Vamos a comer algo.", "Let's eat something."],
      ["Vamos a intentarlo otra vez.", "Let's try it again."]
    ],
    "hola": [
      ["Hola, ¿qué tal?", "Hi, how's it going?"],
      ["Hola, buenos días.", "Hello, good morning."]
    ],
    "es que": [
      ["Es que no hablo muy bien español.", "It's that I don't speak Spanish very well."],
      ["Es que no entendí la pregunta.", "It's that I didn't understand the question."]
    ]
  }
};
